const TOPICS = [
  {
    slug: 'best-apartment-dogs',
    title: '15 Best Dog Breeds for Apartment Living',
    filter: (b) => (b.size === 'toy' || b.size === 'small' || b.size === 'medium') && b.energy !== 'high' && b.barking !== 'high',
    desc: 'small to medium size, low/medium energy, not heavy barkers',
  },
  {
    slug: 'low-shedding-dogs',
    title: '15 Dog Breeds That Barely Shed',
    filter: (b) => b.shedding === 'low',
    desc: 'low shedding, hypoallergenic or minimal coat loss',
  },
  {
    slug: 'best-family-dogs',
    title: '15 Best Family Dogs for Households With Kids',
    filter: (b) => b.good_with_kids === true && b.trainability !== 'hard',
    desc: 'great with children, gentle, predictable temperament',
  },
  {
    slug: 'smartest-dog-breeds',
    title: '15 Smartest Dog Breeds Ranked',
    filter: (b) => b.trainability === 'easy' && b.temperament.includes('intelligent'),
    desc: 'highly intelligent, easy to train, problem solvers',
  },
  {
    slug: 'best-dogs-for-seniors',
    title: '15 Best Dog Breeds for Seniors and Retirees',
    filter: (b) => b.energy === 'low' && b.size !== 'giant' && b.grooming !== 'high',
    desc: 'low energy, small to medium, easy care, calm',
  },
  {
    slug: 'low-maintenance-dogs',
    title: '15 Low-Maintenance Dog Breeds for Busy Owners',
    filter: (b) => b.grooming === 'low' && b.energy !== 'high',
    desc: 'minimal grooming, low/medium energy, independent',
  },
  {
    slug: 'best-watchdog-breeds',
    title: '15 Best Watchdog Breeds for Home Security',
    filter: (b) => b.temperament.includes('alert') || b.temperament.includes('protective'),
    desc: 'alert, vocal when needed, protective instinct',
  },
  {
    slug: 'best-dogs-for-first-time-owners',
    title: '15 Best Dog Breeds for First-Time Owners',
    filter: (b) => b.trainability === 'easy' && (b.temperament.includes('gentle') || b.temperament.includes('friendly')),
    desc: 'easy to train, forgiving, even temperament',
  },
  {
    slug: 'cuddliest-dog-breeds',
    title: '15 Cuddliest Dog Breeds That Love Affection',
    filter: (b) => b.temperament.includes('affectionate'),
    desc: 'highly affectionate, velcro personality, love physical contact',
  },
  {
    slug: 'best-cold-weather-dogs',
    title: '15 Dog Breeds That Thrive in Cold Weather',
    filter: (b) => b.cold_tolerance === 'high',
    desc: 'built for cold climates, thick double coat, arctic or mountain origin',
  },
  {
    slug: 'best-hot-weather-dogs',
    title: '15 Dog Breeds That Handle Hot Weather Well',
    filter: (b) => b.hot_tolerance === 'high',
    desc: 'heat-tolerant, short single coat, lean build',
  },
  {
    slug: 'best-running-dogs',
    title: '15 Best Dog Breeds for Runners and Joggers',
    filter: (b) => b.energy === 'high' && (b.size === 'medium' || b.size === 'large'),
    desc: 'high stamina, athletic, built for sustained running',
  },
  {
    slug: 'best-small-dog-breeds',
    title: '15 Best Small Dog Breeds Under 25 Pounds',
    filter: (b) => b.size === 'toy' || b.size === 'small',
    desc: 'under 25 pounds, great for small homes',
  },
  {
    slug: 'best-medium-dogs',
    title: '15 Best Medium-Sized Dog Breeds',
    filter: (b) => b.size === 'medium',
    desc: 'versatile medium size, 25-60 pounds',
  },
  {
    slug: 'best-large-dog-breeds',
    title: '15 Best Large Dog Breeds for Spacious Homes',
    filter: (b) => b.size === 'large' || b.size === 'giant',
    desc: 'large to giant size, manageable temperament',
  },
  {
    slug: 'most-affectionate-breeds',
    title: '15 Most Affectionate Dog Breeds',
    filter: (b) => b.temperament.includes('affectionate') || b.temperament.includes('gentle'),
    desc: 'people-oriented, expressive, strong human bond',
  },
  {
    slug: 'quietest-dog-breeds',
    title: '15 Quietest Dog Breeds That Rarely Bark',
    filter: (b) => b.barking === 'low',
    desc: 'low vocalization, calm, noise-sensitive home friendly',
  },
  {
    slug: 'best-dogs-for-cats',
    title: '15 Dog Breeds That Get Along Best With Cats',
    filter: (b) => b.good_with_cats === true,
    desc: 'low prey drive, calm around small animals',
  },
  {
    slug: 'best-emotional-support-dogs',
    title: '15 Best Dog Breeds for Emotional Companionship',
    filter: (b) => b.temperament.includes('affectionate') && b.energy !== 'high',
    desc: 'intuitive, calm, deeply bonded to their person',
  },
  {
    slug: 'best-active-lifestyle-dogs',
    title: '15 Best Dog Breeds for Active Lifestyles',
    filter: (b) => b.energy === 'high',
    desc: 'high energy, athletic, needs lots of exercise',
  },
  {
    slug: 'easiest-to-train-breeds',
    title: '15 Easiest Dog Breeds to Train',
    filter: (b) => b.trainability === 'easy',
    desc: 'eager to please, fast learners, obedience champions',
  },
  {
    slug: 'best-guard-dog-breeds',
    title: '15 Best Guard Dog Breeds for Property Protection',
    filter: (b) => b.temperament.includes('protective') && (b.size === 'large' || b.size === 'giant'),
    desc: 'protective, strong, courageous, territorial',
  },
  {
    slug: 'fluffiest-dog-breeds',
    title: '15 Fluffiest Dog Breeds That Look Like Teddy Bears',
    filter: (b) => b.coat.includes('long') || b.coat.includes('fluffy') || b.coat.includes('double'),
    desc: 'long plush coats, teddy bear appearance, photogenic',
  },
  {
    slug: 'most-loyal-dog-breeds',
    title: '15 Most Loyal Dog Breeds That Bond for Life',
    filter: (b) => b.temperament.includes('loyal'),
    desc: 'devoted, one-family dog, strong bond',
  },
  {
    slug: 'calm-dog-breeds',
    title: '15 Calm Dog Breeds Perfect for Quiet Homes',
    filter: (b) => b.energy === 'low' && b.barking !== 'high',
    desc: 'mellow, low energy, quiet disposition',
  },
  {
    slug: 'best-dogs-for-rv-living',
    title: '15 Best Dog Breeds for RV and Van Life',
    filter: (b) => (b.size === 'toy' || b.size === 'small' || b.size === 'medium') && b.energy !== 'high',
    desc: 'travel-tolerant, adaptable, calm in small spaces',
  },
  {
    slug: 'best-multi-dog-breeds',
    title: '15 Dog Breeds That Thrive With Other Dogs',
    filter: (b) => b.good_with_other_dogs === true,
    desc: 'pack-friendly, social, low same-sex aggression',
  },
  {
    slug: 'longest-living-dog-breeds',
    title: '15 Dog Breeds With the Longest Lifespans',
    filter: (b) => b.lifespan_min >= 12,
    desc: 'average lifespan 13+ years, hardy constitution',
  },
  {
    slug: 'rarest-dog-breeds',
    title: '15 Rarest Dog Breeds Most People Have Never Heard Of',
    filter: (b) => b.rare === true,
    desc: 'low registration numbers, regional or historic breeds',
  },
  {
    slug: 'best-dogs-for-couples',
    title: '15 Best Dog Breeds for Couples Without Kids',
    filter: (b) => (b.size === 'small' || b.size === 'medium') && b.energy === 'medium' && b.trainability !== 'hard',
    desc: 'adaptable, social, good for two-adult households',
  },
];

module.exports = { TOPICS };
