const TOPICS = [
  { slug: 'best-apartment-dogs', title: '15 Best Dog Breeds for Apartment Living', filter: 'small to medium size, low-to-moderate energy, quiet temperament, adaptable to small spaces' },
  { slug: 'low-shedding-dogs', title: '15 Dog Breeds That Barely Shed', filter: 'hypoallergenic coats, low-shedding, single-coated or curly-coated' },
  { slug: 'best-family-dogs', title: '15 Best Family Dogs for Households With Kids', filter: 'gentle, patient with children, sturdy build, predictable temperament' },
  { slug: 'smartest-dog-breeds', title: '15 Smartest Dog Breeds Ranked', filter: 'high working/obedience intelligence, learn commands quickly, problem-solvers' },
  { slug: 'best-dogs-for-seniors', title: '15 Best Dog Breeds for Seniors and Retirees', filter: 'low energy needs, small to medium size, affectionate, easy to handle' },
  { slug: 'low-maintenance-dogs', title: '15 Low-Maintenance Dog Breeds for Busy Owners', filter: 'minimal grooming, independent, healthy breeds, easy care routines' },
  { slug: 'best-watchdog-breeds', title: '15 Best Watchdog Breeds for Home Security', filter: 'alert, protective, vocal when needed, trainable, loyal to family' },
  { slug: 'best-dogs-for-first-time-owners', title: '15 Best Dog Breeds for First-Time Owners', filter: 'easy to train, forgiving of mistakes, even temperament, well-documented breed' },
  { slug: 'cuddliest-dog-breeds', title: '15 Cuddliest Dog Breeds That Love Affection', filter: 'highly affectionate, velcro temperament, lap-dog tendencies, bond-oriented' },
  { slug: 'best-cold-weather-dogs', title: '15 Dog Breeds That Thrive in Cold Weather', filter: 'thick double coat, arctic or mountain origin, cold-tolerant' },
  { slug: 'best-hot-weather-dogs', title: '15 Dog Breeds That Handle Hot Weather Well', filter: 'short single coat, lean build, low exercise needs in heat, desert or tropical origin' },
  { slug: 'best-running-dogs', title: '15 Best Dog Breeds for Runners and Joggers', filter: 'high stamina, athletic build, exercise-tolerant, weatherproof coat' },
  { slug: 'best-small-dog-breeds', title: '15 Best Small Dog Breeds Under 20 Pounds', filter: 'adult weight under 20 pounds, suitable for small spaces, well-tempered' },
  { slug: 'best-medium-dogs', title: '15 Best Medium-Sized Dog Breeds', filter: 'adult weight 25-55 pounds, versatile, family-friendly' },
  { slug: 'best-large-dog-breeds', title: '15 Best Large Dog Breeds for Spacious Homes', filter: 'adult weight 60-100 pounds, gentle giants, manageable temperament' },
  { slug: 'most-affectionate-breeds', title: '15 Most Affectionate Dog Breeds', filter: 'highly social, people-oriented, expressive, bond strongly with humans' },
  { slug: 'quietest-dog-breeds', title: '15 Quietest Dog Breeds That Rarely Bark', filter: 'low vocalization, calm temperament, suitable for noise-sensitive homes' },
  { slug: 'best-dogs-for-cats', title: '15 Dog Breeds That Get Along Best With Cats', filter: 'low prey drive, calm around small animals, sociable temperament' },
  { slug: 'best-emotional-support-dogs', title: '15 Best Dog Breeds for Emotional Companionship', filter: 'intuitive, calm, affectionate, attentive to human moods, easy-going' },
  { slug: 'best-active-lifestyle-dogs', title: '15 Best Dog Breeds for Active Lifestyles', filter: 'high exercise needs, athletic, energetic, suited for daily activity' },
  { slug: 'easiest-to-train-breeds', title: '15 Easiest Dog Breeds to Train', filter: 'eager to please, fast learners, obedience-trial favorites' },
  { slug: 'best-guard-dog-breeds', title: '15 Best Guard Dog Breeds for Property Protection', filter: 'protective, strong, courageous, trainable, territorial when needed' },
  { slug: 'fluffiest-dog-breeds', title: '15 Fluffiest Dog Breeds That Look Like Teddy Bears', filter: 'long thick coats, plush appearance, fluffy texture, photogenic' },
  { slug: 'most-loyal-dog-breeds', title: '15 Most Loyal Dog Breeds That Bond for Life', filter: 'one-person breeds or family-loyal, devoted temperament, faithful' },
  { slug: 'calm-dog-breeds', title: '15 Calm Dog Breeds Perfect for Quiet Homes', filter: 'low-energy, mellow, calm temperament, gentle disposition' },
  { slug: 'best-dogs-for-rv-living', title: '15 Best Dog Breeds for RV and Van Life', filter: 'travel-tolerant, adaptable to small spaces, calm in transit' },
  { slug: 'best-multi-dog-breeds', title: '15 Dog Breeds That Thrive With Other Dogs', filter: 'pack-oriented, dog-friendly, social, low same-sex aggression' },
  { slug: 'longest-living-dog-breeds', title: '15 Dog Breeds With the Longest Lifespans', filter: 'average lifespan 13+ years, healthy genetic line, hardy constitution' },
  { slug: 'rarest-dog-breeds', title: '15 Rarest Dog Breeds Most People Have Never Heard Of', filter: 'low registration numbers, regional or historic breeds, unique appearance' },
  { slug: 'best-dogs-for-couples', title: '15 Best Dog Breeds for Couples Without Kids', filter: 'medium energy, adaptable, social, suitable for two-adult households' },
];

module.exports = { TOPICS };
